### PR TITLE
Create configuration for Travis and Cloud Foundry

### PR DESCRIPTION
**Pull request by TobyRet**

### CODE REVIEW

**Comment by TobyRet** [comment]
@govuklaurence - is the only way to skip a build on Travis by adding '[ci skip]' to the commit message? Couldn't see anything regarding configuring .travis.yml for this purpose

**Comment by govuklaurence** [comment]
Why do you want to skip?

**Review by govuklaurence — APPROVED** [review]
LGTM

**Comment by TobyRet** [comment]
The end to end tests don't have their own tests @govuklaurence

**Pull request merged**
